### PR TITLE
Add file for beginner to test forking and pushing.

### PR DESCRIPTION
**Pull request by atieq-khan**

### CODE REVIEW

**Comment by atieq-khan** [comment]
Sorry, that i forgot to add a description. this is description:
"added a file for beginner and any to test the forking and push for github"
This is due to the if in case is want to know that how to push and fork a repo.

**Comment by jonhoo** [comment]
Hi there! Out of curiosity, what made you decide to submit this PR? Are you taking some kind of class or something that encouraged you to try this?

**Comment by atieq-khan** [comment]
I am currently doing training at knowledge Stream. The reason is simple I
did this because I had 5 more tasks to do till morning. And I had no idea
that how pull request works. And so, I was worried that will not be able to
complete my tasks till morning. I had to read files and other stuff to find
a typo or improvement.
So, I thought don't have much time. Why not make a file that people can use
to quickly to make changes without worrying anything. And make a pull
request. This way they get the idea of how forking and how pull request
works.

**Comment by jonhoo** [comment]
Ah, what course are you taking there? We got a huge batch of PRs today that mostly seemed like someone being sent to just do some kind of exercise attempting to do some git operations, and it's generating quite a lot of noise on our end. 😅

**Comment by atieq-khan** [comment]
yeah sorry, that was our class doing the tasks. we have a dead line till this morning. 
so, did u like this pull request ?

**Comment by atieq-khan** [comment]
we are taking chip designing course under "10x engineers"

**Comment by jonhoo** [comment]
Thanks for the info!
No, this is not the kind of change that is useful to make on a repository :)

**Pull request closed without merging**
