### PR TITLE
commit by mobeen

### PR DESCRIPTION
**Pull request by mobeen10x**
please accept my merge request i needed this for completion of task

### CODE REVIEW

**Comment by anishathalye** [comment]
We've gotten a bunch of PRs like this recently. Could you please elaborate on why you created this PR? E.g., was it a homework assignment for a class?

**Comment by mobeen10x** [comment]
yes it is homework task for missing semester .

**Comment by anishathalye** [comment]
Thanks! Just to be sure: you're referring to [exercise 7 of the Git lecture](https://missing.csail.mit.edu/2020/version-control/)?

**Comment by mobeen10x** [comment]
yes version control git

**Comment by anishathalye** [comment]
Thank you! I've updated the wording for the exercise to make it clear that you can skip the exercise if you don't have an improvement to make.

**Pull request closed without merging**
