### PR TITLE
Update version-control.md

### PR DESCRIPTION
**Pull request by gabolbido**
Fixed a typo

### CODE REVIEW

**Comment by jonhoo** [comment]
I'm honestly not sure what the right formatting of this is. It's true that "committed" is the right spelling, but this is really referring to `git commit` as a verb, and taking the past tense of it, which would imply `git commit`ed is right. Just like you might write `git commit`ing (as opposed to `git commit`ting). I personally feel like the version without the extra 't' is more legible, but happy to defer. @anishathalye ?

**Comment by LogaJ** [comment]
Avoiding 'have, had/have or will' in a sentence e.g. "once you commit your changes" rather than "once you have committed your changes" means you always refer to the git function name rather then the verb. 

This is because the git function _commit_ overrides, in this context, the past, present or future forms of the verb.

**Comment by JJGO** [comment]
I find it easier to read without the extra 't'

**Comment by jonhoo** [comment]
I agree — let's leave this as-is then. Thanks for the suggestion though!

**Pull request closed without merging**
