### PR TITLE
Add index_vietnamese.md - a translation in Vietnamese of the index page

### PR DESCRIPTION
**Pull request by lehoangan2906**
I translate the page and correct some typographical errors in previous translations.

### CODE REVIEW

**Comment by anishathalye** [comment]
Did you mean to send this PR to https://missing-semester-vn.github.io/ ?

**Comment by lehoangan2906** [comment]
Yes, that's what I want to do. But this is my first time contributing a translation to this project so I don't know how to do it properly.

**Comment by lehoangan2906** [comment]
> Did you mean to send this PR to https://missing-semester-vn.github.io/ ?

Yes, that's what I want to do. But this is my first time contributing a translation to this project so I don't know how to do it properly.

**Comment by anishathalye** [comment]
No worries. Glad to see you contributing to a GitHub project for the first time!

**Comment by lehoangan2906** [comment]
> No worries. Glad to see you contributing to missing semester for the first time!

So each time I want to contribute something, for example, a translation, all I need to do is create a pull request directly on this branch, right?  Because I don't really know where the source code for each language version is.

**Comment by anishathalye** [comment]
The Vietnamese translation is here: https://github.com/missing-semester-vn/missing-semester-vn.github.io

If you want to contribute something to https://missing.csail.mit.edu/, then send the PR to this repo.

**Comment by lehoangan2906** [comment]
> The Vietnamese translation is here: https://github.com/missing-semester-vn/missing-semester-vn.github.io
> 
> If you want to contribute something to https://missing.csail.mit.edu/, then send the PR to this repo.

Thank you so much for this <3 Hope you have a great day.

**Pull request closed without merging**
