### PR TITLE
fix the typo

### PR DESCRIPTION
**Pull request by lcynot**
fix the typo of "hash function"

### CODE REVIEW

**Comment by anishathalye** [comment]
Thanks!

**Comment by arajoubeha** [comment]
You're welcome — thanks for the feedback!

**Comment by arajoubeha** [comment]
Thanks for the feedback!

**Comment by arajoubeha** [comment]
You're welcome — thanks for the feedback!

**Comment by arajoubeha** [comment]
Thanks for the feedback!

**Pull request merged**
