### PR TITLE
Add Github action workflow to lint prose

### PR DESCRIPTION
**Pull request by tomwhross**
Uses [the first action I've created and published](https://github.com/marketplace/actions/lint-markdown) to run write-good on Markdown files. Works well with `add-pr-comment` to have bot post a comment with the output from `write-good` if there is any. Purely informational; does not fail the check if output is generated.

 - use checkout to access repo files
 - use write-good-action to lint prose in Markdown files
 - use add-pr-comment to add comment to PR with write-good output if any
 - this will never reject a PR or commit based on write-good's output,
   this is informational only, and the PR author is free to ignore as
   write-good can be opinionated

image

### CODE REVIEW

**Comment by tomwhross** [comment]
These triggers work in my repos, but the actions are not being triggered here. Need to look into why that is happening.

**Comment by tomwhross** [comment]
Found the issue: Github actions do no trigger in forked repos, though this is not made clear in the documentation. See https://github.community/t/github-action-not-triggered-on-pull-request/18009 and https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054/12.

I was just curious to get feedback on this as this is using the first action I've published. Feel free to reject.

**Comment by jonhoo** [comment]
Thanks! I think we'll probably pass on this, if only because this project has turned out to be a great way to make people submit their first PR just to fix some typos, which would go away if we merged that :p Otherwise it's a good idea for any _other_ page like this though!

**Comment by tomwhross** [comment]
> Thanks! I think we'll probably pass on this, if only because this project has turned out to be a great way to make people submit their first PR just to fix some typos, which would go away if we merged that :p Otherwise it's a good idea for any _other_ page like this though!

No worries, @jonhoo! I figured that would be the case, plus for an established repo of this size it would be pretty annoying until someone actioned all of the suggestions and warnings. Thanks for the feedback, though, that's all I was really looking for! Really enjoyed the course!

**Pull request closed without merging**
