### PR TITLE
fix paste command in data-wrangling.md

### PR DESCRIPTION
**Pull request by duysmile**

### CODE REVIEW

**Comment by anishathalye** [comment]
Why is this necessary? With no file specified, paste reads from stdin.

**Comment by duysmile** [comment]
> Why is this necessary? With no file specified, paste reads from stdin.

If I don't add "-" character, i received a alert like below and no result respond.
Screen Shot 2021-04-01 at 00 11 53
I ran that command on macOS

**Comment by anishathalye** [comment]
Ah, looks like another difference between GNU paste and BSD paste. @jonhoo thoughts? Should we add the `-`, or add an explanation of the difference between the GNU coreutils version and the BSD version?

**Comment by anishathalye** [comment]
Added an explanation in b3920a273687a3f29f0f3cf67f5c927219b45207.

**Pull request closed without merging**
