### PR TITLE
Add translation URL for Serbian language

### PR DESCRIPTION
**Pull request by marcoroganovic**

### CODE REVIEW

**Comment by JJGO** [comment]
Hi Marko,

First, thanks for spending the time to translate the course.

We were wondering why the site is hosted under a private corporation domain. We ask this mainly because other translations have followed the pattern of using GitHub repositories hosted through GitHub pages.

We like this approach since it makes it easier for us to check that the intent is noncommercial (as the license specifies) and it allows other people to contribute fixes and corrections through pull requests.

Would you consider putting this translation under https://missing-semester-rs.github.io instead?

**Comment by marcoroganovic** [comment]
Hi!

Thanks for your reply.

We never kept any reference to our website, nor we have linked anything from our homepage to it.

We just made design and it was fastest for us to spin it in this way because of some CSS that we didn't need to write from scratch because we have spent a lot of time on translations at that point. All lessons are translated.

People still can contribute fixes and corrections since all the content is public.

https://github.com/netboxify/missing-semester

**Comment by anishathalye** [comment]
Ok, that seems fine. Could you please fix the broken "See here for contribution & translation guidelines." link at the bottom of the homepage? Also, it would be nice if you linked to the GitHub repo you mentioned above on your site itself. (It may be there already, but since I don't understand Serbian, I can't find it)

**Comment by marcoroganovic** [comment]
Hi @anishathalye 

Thanks for the feedback.

We have done the update on the page, but can you please refresh a few times, we think that is some CDN cache.

**Comment by anishathalye** [comment]
Alphabetized and merged in c277c7f8acda9aeef963f5e4b3ac0ad6716e73c5

**Pull request closed without merging**
